BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role,email_address) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','user@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN', 'admin@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('manager','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'manager@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Philippe','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'P.Billeaudeaux@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Steve','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'S.Riley@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Tony','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'T.Dagradi@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Kevin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'K.Griffin@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Joe','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'J.Gelini@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Dan','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'D.Cutler@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Eric','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'E.Belletto@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Mario','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'M.Palmisano@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Justin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'J.Aliperti@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('George','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'G.Porter@gmail.com');


INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Feufollet', 'Feufollet is an Americana/Cajun band from Lafayette, Louisiana.', 'Philippe Billeaudeaux, Kelli Jones-Savoy, Chris Segura, Chris Stafford, Mike Stafford, Andrew Toups', (select user_id from users where email_address = 'P.Billeaudeaux@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Steve Riley and the Mamou Playboys', 'Steve Riley and the Mamou Playboys are an American Cajun band from southern Louisiana. The band formed in 1988 and has since recorded 10 albums, nine of which are on Rounder Records.', 'Steve Riley, Sam Broussard, Brazos Huval, Kevin Dugas, Kevin Wimmer', (select user_id from users where email_address = 'S.Riley@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Astral Project', 'Astral Project is a modern jazz quartet from New Orleans, Louisiana. It was founded by saxophonist Tony Dagradi in 1978 and includes drummer Johnny Vidacovich, bassist James Singleton and 7-string guitarist Steve Masakowski.', 'Tony Dagradi, Johnny Vidacovich, James Singleton, Steve Masakowski', (select user_id from users where email_address = 'T.Dagradi@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Better Than Ezra', 'Better Than Ezra is an American alternative rock band based in New Orleans, Louisiana, and signed with The End Records.', 'Kevin Griffin, Tom Drummond, James Arthur Payne Jr., Michael Jerome', (select user_id from users where email_address = 'K.Griffin@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Cha Wa', 'Cha Wa is a Grammy-nominated Mardi Gras Indian funk band based out of New Orleans, Louisiana. The name Cha Wa is a slang phrase used by Mardi Gras Indian tribes, meaning "here we come."', 'Joe Gelini, Honey Banister', (select user_id from users where email_address = 'J.Gelini@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('The Deslondes', 'The Deslondes are an Americana musical group from New Orleans, Louisiana. Their music blends together influences from folk, rock and roll, bluegrass, R&B, American roots music, blues, gospel, country, and zydeco.', 'Dan Cutler, Sam Doores, Riley Downing, Cameron Snyder, John James Tourville', (select user_id from users where email_address = 'D.Cutler@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Egg Yolk Jubilee', 'Egg Yolk Jubilee is a band based in New Orleans and noted for their eclectic musical style, combining jazz, blues, funk, and rock elements. In addition to traditional stage venues, they also perform as a street-walking brass band, and have released several studio albums.', 'Eric Belletto, Paul Grass, Keith Hajjar, Mike Hogan, Mac McCann, Glenn Grass', (select user_id from users where email_address = 'E.Belletto@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Flow Tribe', 'Flow Tribe is an American funk rock band based in New Orleans, Louisiana. The group contains six members who are all natives of New Orleans. The band was founded in 2004, and was featured on Episode 11 of MTVs The Real World: New Orleans, which aired September 8, 2010.', 'K.C. O''Rorke, John-Michael Early, Russell Olschner, Chad Penot, Bryan Santos, Mario Palmisano', (select user_id from users where email_address = 'M.Palmisano@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('Groovesect', 'Groovesect was founded in 2006 by New Orleans musicians who had played together in various incarnations since they were eighteen, blending syncopated funk beats and jazz rhythms with rock and soul. Since "Uganda" joined the band in the spring of 2007, Groovesect has been voted the #1 Funk Band and #2 Contemporary Jazz Band in the 2007 Best of the Big Easy Awards.', 'Danny Abel, Nick Krawitz, Tim Sullivan, Eric Vogel, Colin Davis, Alfred "Uganda" Roberts, Justin Aliperti', (select user_id from users where email_address = 'J.Aliperti@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, manager_id) VALUES ('The Meters', 'The Meters are an American funk band formed in 1965 in New Orleans by Zigaboo Modeliste (drums), George Porter Jr. (bass), Leo Nocentelli (guitar) and Art Neville (keyboards). The band performed and recorded their own music from the late 1960s until 1977 and played an influential role as backing musicians for other artists.', 'George Porter Jr., Leo Nocentelli, Zigaboo Modeliste, Brian Stoltz, Terrence Houston', (select user_id from users where email_address = 'G.Porter@gmail.com'));

INSERT INTO genre (genre_name) VALUES ('Jazz');
INSERT INTO genre (genre_name) VALUES ('Folk');
INSERT INTO genre (genre_name) VALUES ('Bluegrass');
INSERT INTO genre (genre_name) VALUES ('Rock');
INSERT INTO genre (genre_name) VALUES ('Country');
INSERT INTO genre (genre_name) VALUES ('Americana');
INSERT INTO genre (genre_name) VALUES ('Cajun');
INSERT INTO genre (genre_name) VALUES ('Blues');
INSERT INTO genre (genre_name) VALUES ('Gospel');
INSERT INTO genre (genre_name) VALUES ('R&B');
INSERT INTO genre (genre_name) VALUES ('Zydeco');
INSERT INTO genre (genre_name) VALUES ('Funk');
INSERT INTO genre (genre_name) VALUES ('Soul');

INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Feufollet'), (select genre_id from genre where genre_name = 'Americana'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Feufollet'), (select genre_id from genre where genre_name = 'Cajun'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'), (select genre_id from genre where genre_name = 'Cajun'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Astral Project'), (select genre_id from genre where genre_name = 'Jazz'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Better Than Ezra'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Cha Wa'), (select genre_id from genre where genre_name = 'Funk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Americana'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Folk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Bluegrass'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'R&B'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Blues'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Gospel'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Country'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Zydeco'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Jazz'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Blues'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Folk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Flow Tribe'), (select genre_id from genre where genre_name = 'Funk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Flow Tribe'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Funk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Jazz'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Soul'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Meters'), (select genre_id from genre where genre_name = 'Funk'));

INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Feufollet'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Astral Project'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Better Than Ezra'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Cha Wa'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'The Deslondes'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Egg Yolk Jubilee'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Flow Tribe'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Groovesect'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'The Meters'));

COMMIT TRANSACTION;
